function data_tbl_avg = average_over_subjects(data_tbl, value_vars)
    z = varfun(@isgrouping, data_tbl, 'OutputFormat', 'uniform');
    z = z & ~matches(data_tbl.Properties.VariableNames, ["subject", value_vars]);
    grouping_vars = data_tbl.Properties.VariableNames(z);
    data_tbl_avg = varfun(@(x) table(mean(x), std(x), 'VariableNames', ["mean", "std"]), data_tbl, ...
                 'GroupingVariables', grouping_vars, ...
                 'InputVariables', value_vars, ...
                 'OutputFormat', "table");
    data_tbl_avg = splitvars(data_tbl_avg);
    data_tbl_avg.Properties.VariableNames = erase( ...
        string(data_tbl_avg.Properties.VariableNames), ...
        "Fun_");
    %data_tbl_avg.Properties.VariableNames = erase( ...
    %    string(data_tbl_avg.Properties.VariableNames), ...
    %    "_mean");
    data_tbl_avg = addvars(data_tbl_avg, repmat("avg", height(data_tbl_avg), 1), 'NewVariableNames', "subject", 'Before', 1);
end

function z = isgrouping(x)
    z = ischar(x) || (~iscell(x) && size(x, 2) == 1);
end
