function [edp] = ecogdatapath(Analysis,BaselineWindow,BoxCar,WindowStart,WindowSize,varargin)
p = inputParser();
addRequired(p, 'Analysis');
addRequired(p, 'BaselineWindow');
addRequired(p, 'BoxCar');
addRequired(p, 'WindowStart');
addRequired(p, 'WindowSize');
addParameter(p, 'root', '/data/chriscox/ECoG/KyotoNaming/data');
parse(p, Analysis,BaselineWindow,BoxCar, WindowStart, WindowSize, varargin{:});

edp = fullfile(p.Results.root, ...
    p.Results.Analysis, ...
    'BaselineWindow', sprintf('%04d', p.Results.BaselineWindow), ...
    'avg', ...
    'BoxCar', sprintf('%03d', p.Results.BoxCar), ...
    'WindowStart', sprintf('%04d', p.Results.WindowStart), ...
    'WindowSize', sprintf('%04d', p.Results.WindowSize));
end
