function embeddings = get_all_embeddings(metadata, results, scale_singular_vectors)
    vars = ["subject", "target_label", "target_type", "sim_source", "sim_metric", ...
        "filters", "FiltersToApplyBeforeEmbedding"];
    func = @(varargin) get_embedding(metadata, varargin{:}, scale_singular_vectors);
    if exists_parpool()
        embeddings = par_rowfun(func, results, ...
                                'InputVariables', vars, ...
                                'ExtractCellContents', true, ...
                                'OutputFormat', "cell");
    else
        embeddings = rowfun(func, results, ...
                            'InputVariables', vars, ...
                            'ExtractCellContents', true, ...
                            'OutputFormat', "cell");
    end
end
