function testsets = get_all_testsets(results, metadata, options)

    arguments
      results
      metadata
      options.cvscheme
    end

    vars = ["subject", "cvholdout", "filters"];
    fun = @(s,cv,f) get_testset(metadata, s, ...
      cvscheme = options.cvscheme, ...
      cvholdout = cv, ...
      filters = f);

    if exists_parpool()
        testsets = par_rowfun(fun, results, ...
                              'InputVariables', vars, ...
                              'ExtractCellContents', true, ...
                              'OutputFormat', "cell");
    else
        testsets = rowfun(fun, results, ...
                          'InputVariables', vars, ...
                          'ExtractCellContents', true, ...
                          'OutputFormat', "cell");
    end
end
