function write_itemwise_corr(results, filename)
    % Add window size/start to each itemwise sub-table
    func = @(window_start, window_size, subject, random_seed, itemwise) ...
        [...
            table(...
                repvec(window_start, height(itemwise)), ...
                repvec(window_size, height(itemwise)), ...
                repvec(subject, height(itemwise)), ...
                repvec(random_seed, height(itemwise)), ...
                'VariableNames', ["window_start", "window_size", "subject", "random_seed"] ...
            ), ...
            itemwise ...
        ];

    tmp = rowfun(func, results, ...
        'InputVariables', ["WindowStart", "WindowSize", "subject", "RandomSeed", "itemwise"], ...
        'ExtractCellContents', true, ...
        'OutputFormat', "cell");
    tbl = cat(1, tmp{:});
    writetable(tbl, filename);
end
